Feat: update to 1.22.5

diff --git a/scripts/Makefile.in b/scripts/Makefile.in
--- a/scripts/Makefile.in
+++ b/scripts/Makefile.in
@@ -112,7 +112,8 @@ am__aclocal_m4_deps = $(top_srcdir)/m4/dpkg-arch.m4 \
 	$(top_srcdir)/m4/dpkg-build.m4 \
 	$(top_srcdir)/m4/dpkg-compiler.m4 \
 	$(top_srcdir)/m4/dpkg-coverage.m4 \
-	$(top_srcdir)/m4/dpkg-funcs.m4 $(top_srcdir)/m4/dpkg-libs.m4 \
+	$(top_srcdir)/m4/dpkg-funcs.m4 \
+	$(top_srcdir)/m4/dpkg-headers.m4 $(top_srcdir)/m4/dpkg-libs.m4 \
 	$(top_srcdir)/m4/dpkg-linker.m4 $(top_srcdir)/m4/dpkg-progs.m4 \
 	$(top_srcdir)/m4/dpkg-types.m4 \
 	$(top_srcdir)/m4/dpkg-unicode.m4 $(top_srcdir)/m4/gettext.m4 \
@@ -126,8 +127,9 @@ am__aclocal_m4_deps = $(top_srcdir)/m4/dpkg-arch.m4 \
 	$(top_srcdir)/configure.ac
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
-DIST_COMMON = $(srcdir)/Makefile.am $(dist_zshcompletions_DATA) \
-	$(nobase_dist_perllib_DATA) $(am__DIST_COMMON)
+DIST_COMMON = $(srcdir)/Makefile.am $(dist_bashcompletions_DATA) \
+	$(dist_zshcompletions_DATA) $(nobase_dist_perllib_DATA) \
+	$(am__DIST_COMMON)
 mkinstalldirs = $(install_sh) -d
 CONFIG_HEADER = $(top_builddir)/config.h
 CONFIG_CLEAN_FILES = Build.PL README.cpan
@@ -160,8 +162,8 @@ am__uninstall_files_from_dir = { \
          $(am__cd) "$$dir" && rm -f $$files; }; \
   }
 am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(sbindir)" \
-	"$(DESTDIR)$(man3dir)" "$(DESTDIR)$(zshcompletionsdir)" \
-	"$(DESTDIR)$(perllibdir)"
+	"$(DESTDIR)$(man3dir)" "$(DESTDIR)$(bashcompletionsdir)" \
+	"$(DESTDIR)$(zshcompletionsdir)" "$(DESTDIR)$(perllibdir)"
 SCRIPTS = $(bin_SCRIPTS) $(sbin_SCRIPTS)
 AM_V_P = $(am__v_P_@AM_V@)
 am__v_P_ = $(am__v_P_@AM_DEFAULT_V@)
@@ -193,7 +195,8 @@ am__can_run_installinfo = \
 man3dir = $(mandir)/man3
 NROFF = nroff
 MANS = $(man3_MANS)
-DATA = $(dist_zshcompletions_DATA) $(nobase_dist_perllib_DATA)
+DATA = $(dist_bashcompletions_DATA) $(dist_zshcompletions_DATA) \
+	$(nobase_dist_perllib_DATA)
 RECURSIVE_CLEAN_TARGETS = mostlyclean-recursive clean-recursive	\
   distclean-recursive maintainer-clean-recursive
 am__recursive_targets = \
@@ -273,10 +276,15 @@ CXXCPP = @CXXCPP@
 CXXDEPMODE = @CXXDEPMODE@
 CXXFLAGS = @CXXFLAGS@
 CYGPATH_W = @CYGPATH_W@
+DEB_DEFAULT_COMPRESSOR = @DEB_DEFAULT_COMPRESSOR@
 DEFS = @DEFS@
 DEPDIR = @DEPDIR@
 DLLTOOL = @DLLTOOL@
 DOXYGEN = @DOXYGEN@
+DPKG_DEFAULT_PAGER = @DPKG_DEFAULT_PAGER@
+DPKG_DEFAULT_SHELL = @DPKG_DEFAULT_SHELL@
+DPKG_PAGER = @DPKG_PAGER@
+DPKG_SHELL = @DPKG_SHELL@
 DSYMUTIL = @DSYMUTIL@
 DUMPBIN = @DUMPBIN@
 ECHO_C = @ECHO_C@
@@ -360,6 +368,7 @@ POD2MAN = @POD2MAN@
 POSUB = @POSUB@
 PS_LIBS = @PS_LIBS@
 RANLIB = @RANLIB@
+RT_LIBS = @RT_LIBS@
 SED = @SED@
 SELINUX_CFLAGS = @SELINUX_CFLAGS@
 SELINUX_LIBS = @SELINUX_LIBS@
@@ -386,6 +395,7 @@ ac_ct_AR = @ac_ct_AR@
 ac_ct_CC = @ac_ct_CC@
 ac_ct_CXX = @ac_ct_CXX@
 ac_ct_DUMPBIN = @ac_ct_DUMPBIN@
+aclocaldir = @aclocaldir@
 admindir = @admindir@
 am__include = @am__include@
 am__leading_dot = @am__leading_dot@
@@ -393,6 +403,7 @@ am__quote = @am__quote@
 am__tar = @am__tar@
 am__untar = @am__untar@
 backupsdir = @backupsdir@
+bashcompletionsdir = @bashcompletionsdir@
 bindir = @bindir@
 build = @build@
 build_alias = @build_alias@
@@ -404,6 +415,7 @@ datadir = @datadir@
 datarootdir = @datarootdir@
 devlibdir = @devlibdir@
 docdir = @docdir@
+docspecdir = @docspecdir@
 dvidir = @dvidir@
 exec_prefix = @exec_prefix@
 host = @host@
@@ -421,10 +433,14 @@ localedir = @localedir@
 localstatedir = @localstatedir@
 logdir = @logdir@
 mandir = @mandir@
+methodsdir = @methodsdir@
 mkdir_p = @mkdir_p@
 oldincludedir = @oldincludedir@
 pdfdir = @pdfdir@
+perllibdir = @perllibdir@
 pkgconfdir = @pkgconfdir@
+pkgconfigdir = @pkgconfigdir@
+polkitactionsdir = @polkitactionsdir@
 prefix = @prefix@
 program_transform_name = @program_transform_name@
 psdir = @psdir@
@@ -439,56 +455,24 @@ top_builddir = @top_builddir@
 top_srcdir = @top_srcdir@
 zshcompletionsdir = @zshcompletionsdir@
 SUBDIRS = mk po
-sbin_SCRIPTS = \
-	dpkg-fsys-usrunmess \
-	# EOL
-
-bin_SCRIPTS = \
-	dpkg-architecture \
-	dpkg-buildflags \
-	dpkg-buildpackage \
-	dpkg-checkbuilddeps \
-	dpkg-distaddfile \
-	dpkg-genbuildinfo \
-	dpkg-genchanges \
-	dpkg-gencontrol \
-	dpkg-gensymbols \
-	dpkg-mergechangelogs \
-	dpkg-name \
-	dpkg-parsechangelog \
-	dpkg-scanpackages \
-	dpkg-scansources \
-	dpkg-shlibdeps \
-	dpkg-source \
-	dpkg-vendor \
-	# EOL
-
-EXTRA_DIST = dpkg-architecture.pl dpkg-buildflags.pl \
-	dpkg-buildpackage.pl dpkg-checkbuilddeps.pl \
-	dpkg-distaddfile.pl dpkg-fsys-usrunmess.pl \
-	dpkg-genbuildinfo.pl dpkg-genchanges.pl dpkg-gencontrol.pl \
-	dpkg-gensymbols.pl dpkg-mergechangelogs.pl dpkg-name.pl \
-	dpkg-parsechangelog.pl dpkg-scanpackages.pl \
+EXTRA_DIST = Test/Dpkg.pm dpkg-architecture.pl dpkg-buildapi.pl \
+	dpkg-buildflags.pl dpkg-buildpackage.pl dpkg-buildtree.pl \
+	dpkg-checkbuilddeps.pl dpkg-distaddfile.pl \
+	dpkg-fsys-usrunmess.pl dpkg-genbuildinfo.pl dpkg-genchanges.pl \
+	dpkg-gencontrol.pl dpkg-gensymbols.pl dpkg-mergechangelogs.pl \
+	dpkg-name.pl dpkg-parsechangelog.pl dpkg-scanpackages.pl \
 	dpkg-scansources.pl dpkg-shlibdeps.pl dpkg-source.pl \
-	dpkg-vendor.pl $(test_scripts) $(test_data) Test/Dpkg.pm # EOL
-dist_zshcompletions_DATA = \
-	completion/zsh/_dpkg-parsechangelog \
-	# EOL
-
-CLEANFILES = \
-	$(test_data_objects) \
-	$(sbin_SCRIPTS) \
-	$(bin_SCRIPTS) \
-	# EOL
-
-perllibdir = $(PERL_LIBDIR)
+	dpkg-vendor.pl $(test_scripts) $(test_data) # EOL
+CLEANFILES = $(sbin_SCRIPTS) $(bin_SCRIPTS) $(test_data_objects) # EOL
 nobase_dist_perllib_DATA = \
 	Dpkg/Arch.pm \
+	Dpkg/BuildAPI.pm \
 	Dpkg/BuildEnv.pm \
 	Dpkg/BuildFlags.pm \
 	Dpkg/BuildInfo.pm \
 	Dpkg/BuildOptions.pm \
 	Dpkg/BuildProfiles.pm \
+	Dpkg/BuildTree.pm \
 	Dpkg/BuildTypes.pm \
 	Dpkg/Build/Info.pm \
 	Dpkg/Changelog.pm \
@@ -507,6 +491,7 @@ nobase_dist_perllib_DATA = \
 	Dpkg/Control/Fields.pm \
 	Dpkg/Control/Info.pm \
 	Dpkg/Control/HashCore.pm \
+	Dpkg/Control/HashCore/Tie.pm \
 	Dpkg/Control/Hash.pm \
 	Dpkg/Control/Tests.pm \
 	Dpkg/Control/Tests/Entry.pm \
@@ -539,6 +524,7 @@ nobase_dist_perllib_DATA = \
 	Dpkg/Path.pm \
 	Dpkg/Shlibs.pm \
 	Dpkg/Shlibs/Objdump.pm \
+	Dpkg/Shlibs/Objdump/Object.pm \
 	Dpkg/Shlibs/Symbol.pm \
 	Dpkg/Shlibs/SymbolFile.pm \
 	Dpkg/Shlibs/Cppfilt.pm \
@@ -557,7 +543,6 @@ nobase_dist_perllib_DATA = \
 	Dpkg/Source/Patch.pm \
 	Dpkg/Source/Quilt.pm \
 	Dpkg/Substvars.pm \
-	Dpkg/Vars.pm \
 	Dpkg/Vendor.pm \
 	Dpkg/Vendor/Debian.pm \
 	Dpkg/Vendor/Default.pm \
@@ -565,6 +550,39 @@ nobase_dist_perllib_DATA = \
 	Dpkg/Vendor/Ubuntu.pm \
 	Dpkg/Version.pm \
 	Dpkg.pm \
+	# EOL
+
+sbin_SCRIPTS = \
+	dpkg-fsys-usrunmess \
+	# EOL
+
+bin_SCRIPTS = \
+	dpkg-architecture \
+	dpkg-buildflags \
+	dpkg-buildapi \
+	dpkg-buildpackage \
+	dpkg-buildtree \
+	dpkg-checkbuilddeps \
+	dpkg-distaddfile \
+	dpkg-genbuildinfo \
+	dpkg-genchanges \
+	dpkg-gencontrol \
+	dpkg-gensymbols \
+	dpkg-mergechangelogs \
+	dpkg-name \
+	dpkg-parsechangelog \
+	dpkg-scanpackages \
+	dpkg-scansources \
+	dpkg-shlibdeps \
+	dpkg-source \
+	dpkg-vendor \
+	# EOL
+
+dist_bashcompletions_DATA = \
+	# EOL
+
+dist_zshcompletions_DATA = \
+	completion/zsh/_dpkg-parsechangelog \
 	# EOL
 
 
@@ -577,6 +595,7 @@ do_shell_subst = $(AM_V_GEN) $(SED) \
 	-e "s:^BACKUPSDIR=.*$$:BACKUPSDIR='$(backupsdir)':" \
 	-e "s:^PKGDATADIR_DEFAULT=.*$$:PKGDATADIR_DEFAULT='$(pkgdatadir)':" \
 	-e "s:^version=['\"][^'\"]*[\"']:version=\"$(PACKAGE_VERSION)\":" \
+	-e "s:^TAR=.*$$:TAR='$(TAR)':" \
 	# EOL
 
 
@@ -599,6 +618,12 @@ do_make_subst = $(AM_V_GEN) $(SED) \
 	-e "s:dpkg_datadir[[:space:]]*=[[:space:]]*[^[:space:]]*:dpkg_datadir = $(pkgdatadir):" \
 	# EOL
 
+POD2MAN_OPTS = \
+	--utf8 \
+	--release=$(PACKAGE_VERSION) \
+	--date='$(PACKAGE_RELEASE_DATE)' \
+	# EOL
+
 TEST_ENV_VARS = \
 	DPKG_PROGTAR=$(TAR) \
 	DPKG_PROGPATCH=$(PATCH) \
@@ -615,12 +640,14 @@ test_scripts = \
 	t/Dpkg_Package.t \
 	t/Dpkg_Shlibs_Cppfilt.t \
 	t/Dpkg_Shlibs.t \
+	t/Dpkg_BuildAPI.t \
 	t/Dpkg_BuildEnv.t \
 	t/Dpkg_BuildFlags.t \
 	t/Dpkg_BuildFlags_Ubuntu.t \
 	t/Dpkg_BuildInfo.t \
 	t/Dpkg_BuildOptions.t \
 	t/Dpkg_BuildProfiles.t \
+	t/Dpkg_BuildTree.t \
 	t/Dpkg_BuildTypes.t \
 	t/Dpkg_Checksums.t \
 	t/Dpkg_ErrorHandling.t \
@@ -632,7 +659,6 @@ test_scripts = \
 	t/Dpkg_Conf.t \
 	t/Dpkg_Deps.t \
 	t/Dpkg_Path.t \
-	t/Dpkg_Vars.t \
 	t/Dpkg_Interface_Storable.t \
 	t/Dpkg_OpenPGP_KeyHandle.t \
 	t/Dpkg_OpenPGP.t \
@@ -655,11 +681,18 @@ test_scripts = \
 	t/Dpkg_Dist_Files.t \
 	t/dpkg_source.t \
 	t/dpkg_buildpackage.t \
-	t/merge_changelogs.t \
+	t/dpkg_mergechangelogs.t \
 	t/mk.t \
 	# EOL
 
 test_data = \
+	t/Dpkg_BuildAPI/ctrl-api-default \
+	t/Dpkg_BuildAPI/ctrl-api-desync \
+	t/Dpkg_BuildAPI/ctrl-api-explicit \
+	t/Dpkg_BuildAPI/ctrl-api-gt-max \
+	t/Dpkg_BuildAPI/ctrl-api-no-int \
+	t/Dpkg_BuildAPI/ctrl-api-no-ver \
+	t/Dpkg_BuildAPI/ctrl-api-rel-noeq \
 	t/Dpkg_Changelog/countme \
 	t/Dpkg_Changelog/date-format \
 	t/Dpkg_Changelog/fields \
@@ -746,37 +779,45 @@ test_data = \
 	t/Dpkg_Substvars/substvars1 \
 	t/Dpkg_Substvars/substvars2 \
 	t/dpkg_buildpackage/dpkgdb/status \
+	t/dpkg_buildpackage/hook \
 	t/dpkg_buildpackage/test-source_0.dsc \
 	t/dpkg_buildpackage/test-source_0_all.changes \
+	t/dpkg_buildpackage/test-source_0_all.hook \
 	t/dpkg_buildpackage/test-source_0_any.changes \
+	t/dpkg_buildpackage/test-source_0_any.hook \
 	t/dpkg_buildpackage/test-source_0_binary.changes \
+	t/dpkg_buildpackage/test-source_0_binary.hook \
 	t/dpkg_buildpackage/test-source_0_full.changes \
+	t/dpkg_buildpackage/test-source_0_full.hook \
 	t/dpkg_buildpackage/test-source_0_source.changes \
+	t/dpkg_buildpackage/test-source_0_source.hook \
+	t/dpkg_mergechangelogs/ch-a \
+	t/dpkg_mergechangelogs/ch-b \
+	t/dpkg_mergechangelogs/ch-badver-a \
+	t/dpkg_mergechangelogs/ch-badver-b \
+	t/dpkg_mergechangelogs/ch-badver-merged \
+	t/dpkg_mergechangelogs/ch-badver-old \
+	t/dpkg_mergechangelogs/ch-merged \
+	t/dpkg_mergechangelogs/ch-merged-basic \
+	t/dpkg_mergechangelogs/ch-merged-pr \
+	t/dpkg_mergechangelogs/ch-merged-pr-basic \
+	t/dpkg_mergechangelogs/ch-old \
+	t/dpkg_mergechangelogs/ch-unreleased-a \
+	t/dpkg_mergechangelogs/ch-unreleased-b \
+	t/dpkg_mergechangelogs/ch-unreleased-merged \
+	t/dpkg_mergechangelogs/ch-unreleased-merged-basic \
+	t/dpkg_mergechangelogs/ch-unreleased-old \
 	t/dpkg_source/testsuite_0.dsc \
 	t/dpkg_source/testsuite_1.dsc \
 	t/dpkg_source/testsuite_2.dsc \
 	t/dpkg_source/testsuite_3.dsc \
-	t/merge_changelogs/ch-a \
-	t/merge_changelogs/ch-b \
-	t/merge_changelogs/ch-badver-a \
-	t/merge_changelogs/ch-badver-b \
-	t/merge_changelogs/ch-badver-merged \
-	t/merge_changelogs/ch-badver-old \
-	t/merge_changelogs/ch-merged \
-	t/merge_changelogs/ch-merged-basic \
-	t/merge_changelogs/ch-merged-pr \
-	t/merge_changelogs/ch-merged-pr-basic \
-	t/merge_changelogs/ch-old \
-	t/merge_changelogs/ch-unreleased-a \
-	t/merge_changelogs/ch-unreleased-b \
-	t/merge_changelogs/ch-unreleased-merged \
-	t/merge_changelogs/ch-unreleased-merged-basic \
-	t/merge_changelogs/ch-unreleased-old \
 	t/mk/architecture.mk \
+	t/mk/buildapi.mk \
 	t/mk/buildflags.mk \
 	t/mk/buildopts.mk \
 	t/mk/buildtools.mk \
 	t/mk/debian/changelog \
+	t/mk/debian/control \
 	t/mk/pkg-info.mk \
 	t/mk/vendor-v0.mk \
 	t/mk/vendor-v1.mk \
@@ -953,6 +994,27 @@ uninstall-man3:
 	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^3][0-9a-z]*$$,3,;x' \
 	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
 	dir='$(DESTDIR)$(man3dir)'; $(am__uninstall_files_from_dir)
+install-dist_bashcompletionsDATA: $(dist_bashcompletions_DATA)
+	@$(NORMAL_INSTALL)
+	@list='$(dist_bashcompletions_DATA)'; test -n "$(bashcompletionsdir)" || list=; \
+	if test -n "$$list"; then \
+	  echo " $(MKDIR_P) '$(DESTDIR)$(bashcompletionsdir)'"; \
+	  $(MKDIR_P) "$(DESTDIR)$(bashcompletionsdir)" || exit 1; \
+	fi; \
+	for p in $$list; do \
+	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
+	  echo "$$d$$p"; \
+	done | $(am__base_list) | \
+	while read files; do \
+	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(bashcompletionsdir)'"; \
+	  $(INSTALL_DATA) $$files "$(DESTDIR)$(bashcompletionsdir)" || exit $$?; \
+	done
+
+uninstall-dist_bashcompletionsDATA:
+	@$(NORMAL_UNINSTALL)
+	@list='$(dist_bashcompletions_DATA)'; test -n "$(bashcompletionsdir)" || list=; \
+	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
+	dir='$(DESTDIR)$(bashcompletionsdir)'; $(am__uninstall_files_from_dir)
 install-dist_zshcompletionsDATA: $(dist_zshcompletions_DATA)
 	@$(NORMAL_INSTALL)
 	@list='$(dist_zshcompletions_DATA)'; test -n "$(zshcompletionsdir)" || list=; \
@@ -1161,7 +1223,7 @@ check: check-recursive
 all-am: Makefile $(SCRIPTS) $(MANS) $(DATA)
 installdirs: installdirs-recursive
 installdirs-am:
-	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(man3dir)" "$(DESTDIR)$(zshcompletionsdir)" "$(DESTDIR)$(perllibdir)"; do \
+	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(sbindir)" "$(DESTDIR)$(man3dir)" "$(DESTDIR)$(bashcompletionsdir)" "$(DESTDIR)$(zshcompletionsdir)" "$(DESTDIR)$(perllibdir)"; do \
 	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
 	done
 install: install-recursive
@@ -1215,8 +1277,9 @@ info: info-recursive
 
 info-am:
 
-install-data-am: install-data-local install-dist_zshcompletionsDATA \
-	install-man install-nobase_dist_perllibDATA
+install-data-am: install-data-local install-dist_bashcompletionsDATA \
+	install-dist_zshcompletionsDATA install-man \
+	install-nobase_dist_perllibDATA
 	@$(NORMAL_INSTALL)
 	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
 install-dvi: install-dvi-recursive
@@ -1261,9 +1324,10 @@ ps: ps-recursive
 
 ps-am:
 
-uninstall-am: uninstall-binSCRIPTS uninstall-dist_zshcompletionsDATA \
-	uninstall-local uninstall-man \
-	uninstall-nobase_dist_perllibDATA uninstall-sbinSCRIPTS
+uninstall-am: uninstall-binSCRIPTS uninstall-dist_bashcompletionsDATA \
+	uninstall-dist_zshcompletionsDATA uninstall-local \
+	uninstall-man uninstall-nobase_dist_perllibDATA \
+	uninstall-sbinSCRIPTS
 
 uninstall-man: uninstall-man3
 
@@ -1277,6 +1341,7 @@ uninstall-man: uninstall-man3
 	dvi-am html html-am info info-am install install-am \
 	install-binSCRIPTS install-data install-data-am \
 	install-data-hook install-data-local \
+	install-dist_bashcompletionsDATA \
 	install-dist_zshcompletionsDATA install-dvi install-dvi-am \
 	install-exec install-exec-am install-html install-html-am \
 	install-info install-info-am install-man install-man3 \
@@ -1286,6 +1351,7 @@ uninstall-man: uninstall-man3
 	maintainer-clean maintainer-clean-generic mostlyclean \
 	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
 	tags tags-am uninstall uninstall-am uninstall-binSCRIPTS \
+	uninstall-dist_bashcompletionsDATA \
 	uninstall-dist_zshcompletionsDATA uninstall-local \
 	uninstall-man uninstall-man3 uninstall-nobase_dist_perllibDATA \
 	uninstall-sbinSCRIPTS
@@ -1310,11 +1376,13 @@ install-data-local:
 @BUILD_POD_DOC_TRUE@	$(MKDIR_P) $(DESTDIR)$(man3dir)
 @BUILD_POD_DOC_TRUE@	for module in $(nobase_dist_perllib_DATA); do \
 @BUILD_POD_DOC_TRUE@	  name=`echo $$module | $(SED) -e 's|/|::|g' -e 's/\.pm$$//'`; \
-@BUILD_POD_DOC_TRUE@	  $(POD2MAN) --utf8 --center=libdpkg-perl --release=$(VERSION) \
+@BUILD_POD_DOC_TRUE@	  $(POD2MAN) $(POD2MAN_OPTS) --center=libdpkg-perl \
 @BUILD_POD_DOC_TRUE@	    --name="$$name" --section=$(man_perl_section) $(srcdir)/$$module \
 @BUILD_POD_DOC_TRUE@	    >$(DESTDIR)$(man3dir)/$$name.$(man_perl_section); \
-@BUILD_POD_DOC_TRUE@	  test -s $(DESTDIR)$(man3dir)/$$name.$(man_perl_section) || \
-@BUILD_POD_DOC_TRUE@	  rm -f $(DESTDIR)$(man3dir)/$$name.$(man_perl_section); \
+@BUILD_POD_DOC_TRUE@	  if ! [ -s "$(DESTDIR)$(man3dir)/$$name.$(man_perl_section)" ]; then \
+@BUILD_POD_DOC_TRUE@	    echo "error: empty $(man3dir)/$$name.$(man_perl_section)" 2>&1; \
+@BUILD_POD_DOC_TRUE@	    exit 1; \
+@BUILD_POD_DOC_TRUE@	  fi; \
 @BUILD_POD_DOC_TRUE@	done
 
 # Ideally we'd use '$(SED) -i', but unfortunately that's not portable.
